export const dataJob = [
    {
        id: 1,
        userOwner: 'Chonticha Uds',
        name: 'ช่วยงานเทศกาลสงกรานต์',
        jobStatus: 'เปิดรับคนอยู่',
        address: 'แยกลงหาดบางแสน',
        price: 200,
        jobType: 'บาท/วัน',
        worker: ['a', 'b', 'c', 'd'], // person
        genderCondition: 'ชาย',
        beginAge: 18,
        endAge: 40,
        workerAmount: 10,
        description: 'สิ่งประดิษฐ์จากวัสดุเหลือใช้. กำไลข้อมือ กระดาษแข็ง หุ้มด้วยไหมพรม',
        createDate: new Date(2018, 10, 27),
        startDate: new Date(2018, 10, 27),
        endDate: new Date(2018, 10, 27),

    },
    {
        id: 1,
        userOwner: 'Chonticha Uds',
        name: 'ซักผ้า',
        jobStatus: 'เปิดรับคนอยู่',
        address: 'แยกลงหาดบางแสน',
        price: 200,
        jobType: 'บาท/วัน',
        worker: ['a', 'b', 'c', 'd'], // person
        genderCondition: 'ชาย',
        beginAge: 18,
        endAge: 40,
        workerAmount: 10,
        description: 'สิ่งประดิษฐ์จากวัสดุเหลือใช้. กำไลข้อมือ กระดาษแข็ง หุ้มด้วยไหมพรม',
        createDate: new Date(2018, 10, 27),
        startDate: new Date(2018, 10, 27),
        endDate: new Date(2018, 10, 27),

    },
    {
        id: 1,
        userOwner: 'Chonticha Uds',
        name: 'ช่วยงานเทศกาลสงกรานต์',
        jobStatus: 'ไม่รับคนแล้ว',
        address: 'แยกลงหาดบางแสน',
        price: 200,
        jobType: 'บาท/วัน',
        worker: ['a', 'b', 'c', 'd'], // person
        genderCondition: 'ไม่ระบุ',
        beginAge: 18,
        endAge: 40,
        workerAmount: 10,
        description: 'สิ่งประดิษฐ์จากวัสดุเหลือใช้. กำไลข้อมือ กระดาษแข็ง หุ้มด้วยไหมพรม',
        createDate: new Date(2561, 10, 27),
        startDate: new Date(2561, 10, 27),
        endDate: new Date(2561, 10, 27),
    },
    {
        id: 2,
        userOwner: 'Chonticha Uds',
        name: 'ขนของ',
        jobStatus: 'ไม่รับคนแล้ว',
        address: 'แยกลงหาดบางแสน',
        price: 200,
        jobType: 'บาท/วัน',
        worker: ['a', 'b', 'c', 'd'], // person
        genderCondition: 'ไม่ระบุ',
        beginAge: 18,
        endAge: 40,
        workerAmount: 10,
        description: 'สิ่งประดิษฐ์จากวัสดุเหลือใช้. กำไลข้อมือ กระดาษแข็ง หุ้มด้วยไหมพรม',
        createDate: new Date(2561, 10, 27),
        startDate: new Date(2561, 10, 27),
        endDate: new Date(2561, 10, 27),
    },
    {
        id: 2,
        userOwner: 'Chonticha Uds',
        name: 'ขนของ',
        jobStatus: 'ไม่รับคนแล้ว',
        address: 'แยกลงหาดบางแสน',
        price: 200,
        jobType: 'บาท/วัน',
        worker: ['a', 'b', 'c', 'd'], // person
        genderCondition: 'ไม่ระบุ',
        beginAge: 18,
        endAge: 40,
        workerAmount: 10,
        description: 'สิ่งประดิษฐ์จากวัสดุเหลือใช้. กำไลข้อมือ กระดาษแข็ง หุ้มด้วยไหมพรม',
        createDate: new Date(2561, 10, 27),
        startDate: new Date(2561, 10, 27),
        endDate: new Date(2561, 10, 27),
    },
];
